# Generated by Django 3.2.6 on 2021-10-07 23:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mainapp.models


class Migration(migrations.Migration):

    replaces = [('mainapp', '0001_initial'), ('mainapp', '0002_alter_wordstat_gap_after_right_answer'), ('mainapp', '0003_alter_wordstat_gap_after_right_answer'), ('mainapp', '0004_auto_20210810_2126'), ('mainapp', '0005_auto_20210810_2216'), ('mainapp', '0006_auto_20210810_2217'), ('mainapp', '0007_alter_wordstat_gap_after_right_answer'), ('mainapp', '0008_auto_20210811_0033'), ('mainapp', '0009_auto_20210811_0034'), ('mainapp', '0010_auto_20210811_0042'), ('mainapp', '0011_alter_wordstat_gap_after_right_answer'), ('mainapp', '0012_alter_wordstat_gap_after_right_answer'), ('mainapp', '0013_alter_wordstat_gap_after_right_answer'), ('mainapp', '0014_alter_wordstat_gap_after_right_answer'), ('mainapp', '0015_alter_wordstat_gap_after_right_answer'), ('mainapp', '0016_alter_wordstat_gap_after_right_answer'), ('mainapp', '0017_alter_wordstat_next_review'), ('mainapp', '0018_wordstat_skip_lvl_flag'), ('mainapp', '0019_alter_wordstat_memorise_lvl'), ('mainapp', '0020_wordstat_dates'), ('mainapp', '0021_alter_wordstat_dates'), ('mainapp', '0022_alter_wordstat_dates'), ('mainapp', '0023_auto_20210822_1440'), ('mainapp', '0024_auto_20210822_2142'), ('mainapp', '0025_datauserwordstat'), ('mainapp', '0026_auto_20210902_1051'), ('mainapp', '0027_auto_20210902_1241'), ('mainapp', '0028_auto_20210902_1807'), ('mainapp', '0029_auto_20210902_1808'), ('mainapp', '0030_auto_20210902_1837'), ('mainapp', '0031_alter_worddatesstat_word_stat'), ('mainapp', '0032_generalwordsstat_all_words')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('incorrect_answers', models.IntegerField(default=0, verbose_name='Неправильные ответы')),
                ('correct_answers_in_a_row', models.IntegerField(default=0, verbose_name='Правильных ответов подряд')),
                ('memorise_lvl', models.IntegerField(default=1, verbose_name='Уровень запоминания')),
                ('memorise_coefficient', models.IntegerField(default=0, verbose_name='Коеф. запоминания')),
                ('gap_after_right_answer', models.DateTimeField(default=mainapp.models.get_gap_after_answer, verbose_name='Время после правильного ответа')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее повторение')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='Последнее сохранение')),
                ('is_learned', models.BooleanField(default=False, verbose_name='Выучено?')),
                ('is_active_stat', models.BooleanField(default=True, verbose_name='Учитывание статистики')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skip_lvl_flag', models.BooleanField(default=False, verbose_name='Пропуск уровня')),
            ],
            options={
                'verbose_name': 'Статистика слова',
                'verbose_name_plural': 'Статистика слов',
                'ordering': ('next_review',),
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Введите слово кирилицей!', regex='[а-яА-ЯёЁ]')], verbose_name='Слово')),
                ('translation', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Введите перевод латиницей!', regex='[а-яА-ЯёЁ]')], verbose_name='Перевод')),
                ('engex', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Введите пример латиницей!!', regex='[а-яА-ЯёЁ]')], verbose_name='Пример англ.')),
                ('rusex', models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(message='Введите пример кирилицей!', regex='[а-яА-ЯёЁ]')], verbose_name='Пример русс.')),
                ('photoURL', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на миниатюру')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('stat', models.ManyToManyField(related_name='word', to='mainapp.WordStat')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ('word',),
            },
        ),
        migrations.CreateModel(
            name='WordDatesStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('incorrect_answers', models.IntegerField(default=0, verbose_name='Неправильные ответы')),
                ('word_stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_dates_stat', to='mainapp.wordstat', verbose_name='Статистика слова')),
            ],
            options={
                'verbose_name': 'Статистика слова по датам',
                'verbose_name_plural': 'Статистика слов по датам',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='GeneralWordsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильные ответы')),
                ('incorrect_answers', models.IntegerField(default=0, verbose_name='Неправильные ответы')),
                ('new_words', models.IntegerField(default=0, verbose_name='Новые слова')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learned_words', models.IntegerField(default=0, verbose_name='Выучено слов')),
                ('all_words', models.IntegerField(default=0, verbose_name='Все слова')),
            ],
            options={
                'ordering': ('date',),
                'verbose_name': 'Статистика всех слов',
                'verbose_name_plural': 'Статистика всех слов',
            },
        ),
    ]
