# Generated by Django 3.2.6 on 2021-11-18 21:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial_squashed_0032_generalwordsstat_all_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Введите слово латиницей!', regex='[а-яА-ЯёЁ]')], verbose_name='Слово'),
        ),
        migrations.AlterUniqueTogether(
            name='words',
            unique_together={('word', 'translation', 'author')},
        ),
    ]
