# Generated by Django 3.2.6 on 2021-11-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211118_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='words',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='words',
            name='slug',
        ),
    ]
