# Generated by Django 3.2.6 on 2021-11-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211118_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalwordsstat',
            options={'ordering': ('-date',), 'verbose_name': 'Статистика всех слов', 'verbose_name_plural': 'Статистика всех слов'},
        ),
        migrations.AlterModelOptions(
            name='worddatesstat',
            options={'ordering': ('-date',), 'verbose_name': 'Статистика слова по датам', 'verbose_name_plural': 'Статистика слов по датам'},
        ),
    ]
